CREATE TABLE service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    id_parent BIGINT,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_parent) REFERENCES service(id) ON DELETE CASCADE
);

CREATE TABLE abonent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    fio VARCHAR(255) NOT NULL,
    account BIGINT NOT NULL,
    id_service BIGINT NOT NULL,
    FOREIGN KEY (id_service) REFERENCES service (id) ON DELETE CASCADE,
    UNIQUE (id_service, account)
);

INSERT INTO service (id_parent, name)
VALUES
(null, 'service'),
(1, 'ЖКХ'),
(2, 'Отопление'),
(2, 'Вода'),
(4, 'Холодная вода'),
(4, 'Горячая вода'),
(1, 'Детский сад'),
(7, 'Ясли'),
(7, 'Средняя группа'),
(7, 'Старшая группа'),
(1, 'Электроэнергия'),
(1, 'Газ'),
(3, 'Сервис 1'),
(4, 'Сервис 2'),
(8, 'Сервис 3'),
(8, 'Сервис 4'),
(8, 'Сервис 5'),
(1, 'Сервис 6'),
(10, 'Сервис 7'),
(10, 'Сервис 8'),
(1, 'Сервис 9'),
(14, 'Сервис 10'),
(1, 'Сервис 11');

INSERT INTO abonent (fio, account, id_service)
VALUES
('Иванов Иван', 5231456, 7),
('Петров Петр', 12234567, 3),
('Сашин Саша', 12345, 10),
('ФИО', 2423421, 15),
('ФИО 1', 1345765, 4),
('ФИО 2', 34543127, 9),
('ФИО 3', 98081, 3),
('ФИО 4', 13234346, 4),
('ФИО 5', 6786512, 7),
('ФИО 6', 2425136, 13),
('ФИО 7', 674154552, 4),
('ФИО 8', 3241587, 2),
('ФИО 9', 23516754, 14),
('Димин Дима', 12345675, 5);

